In [5]:
import pandas as pd
import datetime
import numpy as np

## Loading Production Data from 1987 to 2008

The production data from these years follows the same file format.

We can therefore import using the same format and put the dataframes into a dictionary.

In 1990 we manually fix well API No: 21451, DUCKETT "A" and set it's well number to 1 as unspecified.
Same in 1991.

In [2]:
dates_cols_oil = ["OIL."+str(i) for i in range(0, 12, 1)]
dates_cols_gas = ["GAS."+str(i)  for i in range(0, 12, 1)]
dates_cols = dates_cols_oil + dates_cols_gas
headers = ['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME','WELL_NO', '  OPER_NO', 'OPER_SUFFIX',
       'OPERATOR', 'ME', 'SECTION', 'TWP','RAN', 'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
           'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE','FORMATION', 'OFB', 'ALLOWABLE_CLASS',
       'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1',
       'YEAR', 'JAN', 'OIL.0', 'GAS.0', 'FEB',
       'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2',
       'APR', 'OIL.3', 'GAS.3', 'MAY', 'OIL.4',
       'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7',
       'SEP', 'OIL.8', 'GAS.8', 'OCT', 'OIL.9',
       'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC',
       'OIL.11', 'GAS.11']

production_data = {}
for i in range(1987, 2016, 1):
    dates_oil = [ "OIL_"+str(datetime.date(i, j+1, 1)) for j in range(0, 12, 1)]
    dates_gas = [ "GAS_"+str(datetime.date(i, j+1, 1)) for j in range(0, 12, 1)]
    renamed_oil = {old: new for old, new in zip(dates_cols_oil, dates_oil)}
    renamed_gas = {old: new for old, new in zip(dates_cols_gas, dates_gas)}
    renamed_cols = {**renamed_oil, **renamed_gas}
    #print(renamed_cols)
    if i != 1994: #No Data from 1994
        print(i)
        if i <= 2008:
            df = pd.read_csv("../raw/"+str(i)+"prodn.txt", delimiter="|", skiprows=[0, 2], names=headers)
            print(df.columns)
            print(renamed_cols)
            df.rename(index=str, columns=renamed_cols, inplace=True)
            df = df.drop(['YEAR','JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL','AUG', 'SEP', 'OCT', 'NOV', 'DEC'], axis=1)
            production_data[i] = df
        else:
            df = pd.read_csv("../raw/"+str(i)+"prodn.txt", delimiter="|")
            df.rename(renamed_cols)
            production_data[i] = df

1987
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1987-06-01', 'GAS.8': 'GAS_1987-09-01', 'GAS.11': 'GAS_1987-12-01', 'OIL.6': 'OIL_1987-07-01', 'OIL.1': 'OIL_1987-02-01', 'OIL.10': 'OIL_1987-11-01', 'GAS.4': 'GAS_1987-05-01', 'OIL.11': 'OIL_1987-12-01', 'GAS.5': 'GAS_1987-06-01', 'OIL.9': 'OIL_1987-10-01', 'OIL.7': 'OIL_1987-08-01', 'GAS.2': 'GAS_1987-03-01', 'OIL.2': 'OIL_1987-03-01', 'GAS.9': 'GAS_1987-10-01', 'GAS.7': 'GAS_1987-08-01', 'GAS.3': 'GAS_1987-04-01', 'GAS.0': 'GAS_1987-01-01', 'GAS.10': 'GAS_1987-11-01', 'OIL.0': 'OIL_1987-01-01', 'OIL.4': 'OIL_1987-05-01', 'OIL.8': 'OIL_1987-09-01', 'OIL.3': 'OIL_1987-04-01', 'GAS.1': 'GAS_1987-02-01', 'GAS.6': 'GAS_1987-07-01'}
1988
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1988-06-01', 'GAS.8': 'GAS_1988-09-01', 'GAS.11': 'GAS_1988-12-01', 'OIL.6': 'OIL_1988-07-01', 'OIL.1': 'OIL_1988-02-01', 'OIL.10': 'OIL_1988-11-01', 'GAS.4': 'GAS_1988-05-01', 'OIL.11': 'OIL_1988-12-01', 'GAS.5': 'GAS_1988-06-01', 'OIL.9': 'OIL_1988-10-01', 'OIL.7': 'OIL_1988-08-01', 'GAS.2': 'GAS_1988-03-01', 'OIL.2': 'OIL_1988-03-01', 'GAS.9': 'GAS_1988-10-01', 'GAS.7': 'GAS_1988-08-01', 'GAS.3': 'GAS_1988-04-01', 'GAS.0': 'GAS_1988-01-01', 'GAS.10': 'GAS_1988-11-01', 'OIL.0': 'OIL_1988-01-01', 'OIL.4': 'OIL_1988-05-01', 'OIL.8': 'OIL_1988-09-01', 'OIL.3': 'OIL_1988-04-01', 'GAS.1': 'GAS_1988-02-01', 'GAS.6': 'GAS_1988-07-01'}
1989

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,5,6,9,16,17,18,19,20,21,28,30,32,33,36,39,42,45,48,51,54,57,60,63,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1989-06-01', 'GAS.8': 'GAS_1989-09-01', 'GAS.11': 'GAS_1989-12-01', 'OIL.6': 'OIL_1989-07-01', 'OIL.1': 'OIL_1989-02-01', 'OIL.10': 'OIL_1989-11-01', 'GAS.4': 'GAS_1989-05-01', 'OIL.11': 'OIL_1989-12-01', 'GAS.5': 'GAS_1989-06-01', 'OIL.9': 'OIL_1989-10-01', 'OIL.7': 'OIL_1989-08-01', 'GAS.2': 'GAS_1989-03-01', 'OIL.2': 'OIL_1989-03-01', 'GAS.9': 'GAS_1989-10-01', 'GAS.7': 'GAS_1989-08-01', 'GAS.3': 'GAS_1989-04-01', 'GAS.0': 'GAS_1989-01-01', 'GAS.10': 'GAS_1989-11-01', 'OIL.0': 'OIL_1989-01-01', 'OIL.4': 'OIL_1989-05-01', 'OIL.8': 'OIL_1989-09-01', 'OIL.3': 'OIL_1989-04-01', 'GAS.1': 'GAS_1989-02-01', 'GAS.6': 'GAS_1989-07-01'}
1990
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1990-06-01', 'GAS.8': 'GAS_1990-09-01', 'GAS.11': 'GAS_1990-12-01', 'OIL.6': 'OIL_1990-07-01', 'OIL.1': 'OIL_1990-02-01', 'OIL.10': 'OIL_1990-11-01', 'GAS.4': 'GAS_1990-05-01', 'OIL.11': 'OIL_1990-12-01', 'GAS.5': 'GAS_1990-06-01', 'OIL.9': 'OIL_1990-10-01', 'OIL.7': 'OIL_1990-08-01', 'GAS.2': 'GAS_1990-03-01', 'OIL.2': 'OIL_1990-03-01', 'GAS.9': 'GAS_1990-10-01', 'GAS.7': 'GAS_1990-08-01', 'GAS.3': 'GAS_1990-04-01', 'GAS.0': 'GAS_1990-01-01', 'GAS.10': 'GAS_1990-11-01', 'OIL.0': 'OIL_1990-01-01', 'OIL.4': 'OIL_1990-05-01', 'OIL.8': 'OIL_1990-09-01', 'OIL.3': 'OIL_1990-04-01', 'GAS.1': 'GAS_1990-02-01', 'GAS.6': 'GAS_1990-07-01'}
1991
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1991-06-01', 'GAS.8': 'GAS_1991-09-01', 'GAS.11': 'GAS_1991-12-01', 'OIL.6': 'OIL_1991-07-01', 'OIL.1': 'OIL_1991-02-01', 'OIL.10': 'OIL_1991-11-01', 'GAS.4': 'GAS_1991-05-01', 'OIL.11': 'OIL_1991-12-01', 'GAS.5': 'GAS_1991-06-01', 'OIL.9': 'OIL_1991-10-01', 'OIL.7': 'OIL_1991-08-01', 'GAS.2': 'GAS_1991-03-01', 'OIL.2': 'OIL_1991-03-01', 'GAS.9': 'GAS_1991-10-01', 'GAS.7': 'GAS_1991-08-01', 'GAS.3': 'GAS_1991-04-01', 'GAS.0': 'GAS_1991-01-01', 'GAS.10': 'GAS_1991-11-01', 'OIL.0': 'OIL_1991-01-01', 'OIL.4': 'OIL_1991-05-01', 'OIL.8': 'OIL_1991-09-01', 'OIL.3': 'OIL_1991-04-01', 'GAS.1': 'GAS_1991-02-01', 'GAS.6': 'GAS_1991-07-01'}
1992
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1992-06-01', 'GAS.8': 'GAS_1992-09-01', 'GAS.11': 'GAS_1992-12-01', 'OIL.6': 'OIL_1992-07-01', 'OIL.1': 'OIL_1992-02-01', 'OIL.10': 'OIL_1992-11-01', 'GAS.4': 'GAS_1992-05-01', 'OIL.11': 'OIL_1992-12-01', 'GAS.5': 'GAS_1992-06-01', 'OIL.9': 'OIL_1992-10-01', 'OIL.7': 'OIL_1992-08-01', 'GAS.2': 'GAS_1992-03-01', 'OIL.2': 'OIL_1992-03-01', 'GAS.9': 'GAS_1992-10-01', 'GAS.7': 'GAS_1992-08-01', 'GAS.3': 'GAS_1992-04-01', 'GAS.0': 'GAS_1992-01-01', 'GAS.10': 'GAS_1992-11-01', 'OIL.0': 'OIL_1992-01-01', 'OIL.4': 'OIL_1992-05-01', 'OIL.8': 'OIL_1992-09-01', 'OIL.3': 'OIL_1992-04-01', 'GAS.1': 'GAS_1992-02-01', 'GAS.6': 'GAS_1992-07-01'}
1993
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1993-06-01', 'GAS.8': 'GAS_1993-09-01', 'GAS.11': 'GAS_1993-12-01', 'OIL.6': 'OIL_1993-07-01', 'OIL.1': 'OIL_1993-02-01', 'OIL.10': 'OIL_1993-11-01', 'GAS.4': 'GAS_1993-05-01', 'OIL.11': 'OIL_1993-12-01', 'GAS.5': 'GAS_1993-06-01', 'OIL.9': 'OIL_1993-10-01', 'OIL.7': 'OIL_1993-08-01', 'GAS.2': 'GAS_1993-03-01', 'OIL.2': 'OIL_1993-03-01', 'GAS.9': 'GAS_1993-10-01', 'GAS.7': 'GAS_1993-08-01', 'GAS.3': 'GAS_1993-04-01', 'GAS.0': 'GAS_1993-01-01', 'GAS.10': 'GAS_1993-11-01', 'OIL.0': 'OIL_1993-01-01', 'OIL.4': 'OIL_1993-05-01', 'OIL.8': 'OIL_1993-09-01', 'OIL.3': 'OIL_1993-04-01', 'GAS.1': 'GAS_1993-02-01', 'GAS.6': 'GAS_1993-07-01'}
1995
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1995-06-01', 'GAS.8': 'GAS_1995-09-01', 'GAS.11': 'GAS_1995-12-01', 'OIL.6': 'OIL_1995-07-01', 'OIL.1': 'OIL_1995-02-01', 'OIL.10': 'OIL_1995-11-01', 'GAS.4': 'GAS_1995-05-01', 'OIL.11': 'OIL_1995-12-01', 'GAS.5': 'GAS_1995-06-01', 'OIL.9': 'OIL_1995-10-01', 'OIL.7': 'OIL_1995-08-01', 'GAS.2': 'GAS_1995-03-01', 'OIL.2': 'OIL_1995-03-01', 'GAS.9': 'GAS_1995-10-01', 'GAS.7': 'GAS_1995-08-01', 'GAS.3': 'GAS_1995-04-01', 'GAS.0': 'GAS_1995-01-01', 'GAS.10': 'GAS_1995-11-01', 'OIL.0': 'OIL_1995-01-01', 'OIL.4': 'OIL_1995-05-01', 'OIL.8': 'OIL_1995-09-01', 'OIL.3': 'OIL_1995-04-01', 'GAS.1': 'GAS_1995-02-01', 'GAS.6': 'GAS_1995-07-01'}
1996
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1996-06-01', 'GAS.8': 'GAS_1996-09-01', 'GAS.11': 'GAS_1996-12-01', 'OIL.6': 'OIL_1996-07-01', 'OIL.1': 'OIL_1996-02-01', 'OIL.10': 'OIL_1996-11-01', 'GAS.4': 'GAS_1996-05-01', 'OIL.11': 'OIL_1996-12-01', 'GAS.5': 'GAS_1996-06-01', 'OIL.9': 'OIL_1996-10-01', 'OIL.7': 'OIL_1996-08-01', 'GAS.2': 'GAS_1996-03-01', 'OIL.2': 'OIL_1996-03-01', 'GAS.9': 'GAS_1996-10-01', 'GAS.7': 'GAS_1996-08-01', 'GAS.3': 'GAS_1996-04-01', 'GAS.0': 'GAS_1996-01-01', 'GAS.10': 'GAS_1996-11-01', 'OIL.0': 'OIL_1996-01-01', 'OIL.4': 'OIL_1996-05-01', 'OIL.8': 'OIL_1996-09-01', 'OIL.3': 'OIL_1996-04-01', 'GAS.1': 'GAS_1996-02-01', 'GAS.6': 'GAS_1996-07-01'}
1997
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1997-06-01', 'GAS.8': 'GAS_1997-09-01', 'GAS.11': 'GAS_1997-12-01', 'OIL.6': 'OIL_1997-07-01', 'OIL.1': 'OIL_1997-02-01', 'OIL.10': 'OIL_1997-11-01', 'GAS.4': 'GAS_1997-05-01', 'OIL.11': 'OIL_1997-12-01', 'GAS.5': 'GAS_1997-06-01', 'OIL.9': 'OIL_1997-10-01', 'OIL.7': 'OIL_1997-08-01', 'GAS.2': 'GAS_1997-03-01', 'OIL.2': 'OIL_1997-03-01', 'GAS.9': 'GAS_1997-10-01', 'GAS.7': 'GAS_1997-08-01', 'GAS.3': 'GAS_1997-04-01', 'GAS.0': 'GAS_1997-01-01', 'GAS.10': 'GAS_1997-11-01', 'OIL.0': 'OIL_1997-01-01', 'OIL.4': 'OIL_1997-05-01', 'OIL.8': 'OIL_1997-09-01', 'OIL.3': 'OIL_1997-04-01', 'GAS.1': 'GAS_1997-02-01', 'GAS.6': 'GAS_1997-07-01'}
1998
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1998-06-01', 'GAS.8': 'GAS_1998-09-01', 'GAS.11': 'GAS_1998-12-01', 'OIL.6': 'OIL_1998-07-01', 'OIL.1': 'OIL_1998-02-01', 'OIL.10': 'OIL_1998-11-01', 'GAS.4': 'GAS_1998-05-01', 'OIL.11': 'OIL_1998-12-01', 'GAS.5': 'GAS_1998-06-01', 'OIL.9': 'OIL_1998-10-01', 'OIL.7': 'OIL_1998-08-01', 'GAS.2': 'GAS_1998-03-01', 'OIL.2': 'OIL_1998-03-01', 'GAS.9': 'GAS_1998-10-01', 'GAS.7': 'GAS_1998-08-01', 'GAS.3': 'GAS_1998-04-01', 'GAS.0': 'GAS_1998-01-01', 'GAS.10': 'GAS_1998-11-01', 'OIL.0': 'OIL_1998-01-01', 'OIL.4': 'OIL_1998-05-01', 'OIL.8': 'OIL_1998-09-01', 'OIL.3': 'OIL_1998-04-01', 'GAS.1': 'GAS_1998-02-01', 'GAS.6': 'GAS_1998-07-01'}
1999
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_1999-06-01', 'GAS.8': 'GAS_1999-09-01', 'GAS.11': 'GAS_1999-12-01', 'OIL.6': 'OIL_1999-07-01', 'OIL.1': 'OIL_1999-02-01', 'OIL.10': 'OIL_1999-11-01', 'GAS.4': 'GAS_1999-05-01', 'OIL.11': 'OIL_1999-12-01', 'GAS.5': 'GAS_1999-06-01', 'OIL.9': 'OIL_1999-10-01', 'OIL.7': 'OIL_1999-08-01', 'GAS.2': 'GAS_1999-03-01', 'OIL.2': 'OIL_1999-03-01', 'GAS.9': 'GAS_1999-10-01', 'GAS.7': 'GAS_1999-08-01', 'GAS.3': 'GAS_1999-04-01', 'GAS.0': 'GAS_1999-01-01', 'GAS.10': 'GAS_1999-11-01', 'OIL.0': 'OIL_1999-01-01', 'OIL.4': 'OIL_1999-05-01', 'OIL.8': 'OIL_1999-09-01', 'OIL.3': 'OIL_1999-04-01', 'GAS.1': 'GAS_1999-02-01', 'GAS.6': 'GAS_1999-07-01'}
2000
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2000-06-01', 'GAS.8': 'GAS_2000-09-01', 'GAS.11': 'GAS_2000-12-01', 'OIL.6': 'OIL_2000-07-01', 'OIL.1': 'OIL_2000-02-01', 'OIL.10': 'OIL_2000-11-01', 'GAS.4': 'GAS_2000-05-01', 'OIL.11': 'OIL_2000-12-01', 'GAS.5': 'GAS_2000-06-01', 'OIL.9': 'OIL_2000-10-01', 'OIL.7': 'OIL_2000-08-01', 'GAS.2': 'GAS_2000-03-01', 'OIL.2': 'OIL_2000-03-01', 'GAS.9': 'GAS_2000-10-01', 'GAS.7': 'GAS_2000-08-01', 'GAS.3': 'GAS_2000-04-01', 'GAS.0': 'GAS_2000-01-01', 'GAS.10': 'GAS_2000-11-01', 'OIL.0': 'OIL_2000-01-01', 'OIL.4': 'OIL_2000-05-01', 'OIL.8': 'OIL_2000-09-01', 'OIL.3': 'OIL_2000-04-01', 'GAS.1': 'GAS_2000-02-01', 'GAS.6': 'GAS_2000-07-01'}
2001
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2001-06-01', 'GAS.8': 'GAS_2001-09-01', 'GAS.11': 'GAS_2001-12-01', 'OIL.6': 'OIL_2001-07-01', 'OIL.1': 'OIL_2001-02-01', 'OIL.10': 'OIL_2001-11-01', 'GAS.4': 'GAS_2001-05-01', 'OIL.11': 'OIL_2001-12-01', 'GAS.5': 'GAS_2001-06-01', 'OIL.9': 'OIL_2001-10-01', 'OIL.7': 'OIL_2001-08-01', 'GAS.2': 'GAS_2001-03-01', 'OIL.2': 'OIL_2001-03-01', 'GAS.9': 'GAS_2001-10-01', 'GAS.7': 'GAS_2001-08-01', 'GAS.3': 'GAS_2001-04-01', 'GAS.0': 'GAS_2001-01-01', 'GAS.10': 'GAS_2001-11-01', 'OIL.0': 'OIL_2001-01-01', 'OIL.4': 'OIL_2001-05-01', 'OIL.8': 'OIL_2001-09-01', 'OIL.3': 'OIL_2001-04-01', 'GAS.1': 'GAS_2001-02-01', 'GAS.6': 'GAS_2001-07-01'}
2002
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2002-06-01', 'GAS.8': 'GAS_2002-09-01', 'GAS.11': 'GAS_2002-12-01', 'OIL.6': 'OIL_2002-07-01', 'OIL.1': 'OIL_2002-02-01', 'OIL.10': 'OIL_2002-11-01', 'GAS.4': 'GAS_2002-05-01', 'OIL.11': 'OIL_2002-12-01', 'GAS.5': 'GAS_2002-06-01', 'OIL.9': 'OIL_2002-10-01', 'OIL.7': 'OIL_2002-08-01', 'GAS.2': 'GAS_2002-03-01', 'OIL.2': 'OIL_2002-03-01', 'GAS.9': 'GAS_2002-10-01', 'GAS.7': 'GAS_2002-08-01', 'GAS.3': 'GAS_2002-04-01', 'GAS.0': 'GAS_2002-01-01', 'GAS.10': 'GAS_2002-11-01', 'OIL.0': 'OIL_2002-01-01', 'OIL.4': 'OIL_2002-05-01', 'OIL.8': 'OIL_2002-09-01', 'OIL.3': 'OIL_2002-04-01', 'GAS.1': 'GAS_2002-02-01', 'GAS.6': 'GAS_2002-07-01'}
2003
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,5,8,15,16,17,18,19,20,27,29,30,33,36,39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2004-06-01', 'GAS.8': 'GAS_2004-09-01', 'GAS.11': 'GAS_2004-12-01', 'OIL.6': 'OIL_2004-07-01', 'OIL.1': 'OIL_2004-02-01', 'OIL.10': 'OIL_2004-11-01', 'GAS.4': 'GAS_2004-05-01', 'OIL.11': 'OIL_2004-12-01', 'GAS.5': 'GAS_2004-06-01', 'OIL.9': 'OIL_2004-10-01', 'OIL.7': 'OIL_2004-08-01', 'GAS.2': 'GAS_2004-03-01', 'OIL.2': 'OIL_2004-03-01', 'GAS.9': 'GAS_2004-10-01', 'GAS.7': 'GAS_2004-08-01', 'GAS.3': 'GAS_2004-04-01', 'GAS.0': 'GAS_2004-01-01', 'GAS.10': 'GAS_2004-11-01', 'OIL.0': 'OIL_2004-01-01', 'OIL.4': 'OIL_2004-05-01', 'OIL.8': 'OIL_2004-09-01', 'OIL.3': 'OIL_2004-04-01', 'GAS.1': 'GAS_2004-02-01', 'GAS.6': 'GAS_2004-07-01'}
2005

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,5,8,15,16,17,18,19,20,27,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2005-06-01', 'GAS.8': 'GAS_2005-09-01', 'GAS.11': 'GAS_2005-12-01', 'OIL.6': 'OIL_2005-07-01', 'OIL.1': 'OIL_2005-02-01', 'OIL.10': 'OIL_2005-11-01', 'GAS.4': 'GAS_2005-05-01', 'OIL.11': 'OIL_2005-12-01', 'GAS.5': 'GAS_2005-06-01', 'OIL.9': 'OIL_2005-10-01', 'OIL.7': 'OIL_2005-08-01', 'GAS.2': 'GAS_2005-03-01', 'OIL.2': 'OIL_2005-03-01', 'GAS.9': 'GAS_2005-10-01', 'GAS.7': 'GAS_2005-08-01', 'GAS.3': 'GAS_2005-04-01', 'GAS.0': 'GAS_2005-01-01', 'GAS.10': 'GAS_2005-11-01', 'OIL.0': 'OIL_2005-01-01', 'OIL.4': 'OIL_2005-05-01', 'OIL.8': 'OIL_2005-09-01', 'OIL.3': 'OIL_2005-04-01', 'GAS.1': 'GAS_2005-02-01', 'GAS.6': 'GAS_2005-07-01'}
2006
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2006-06-01', 'GAS.8': 'GAS_2006-09-01', 'GAS.11': 'GAS_2006-12-01', 'OIL.6': 'OIL_2006-07-01', 'OIL.1': 'OIL_2006-02-01', 'OIL.10': 'OIL_2006-11-01', 'GAS.4': 'GAS_2006-05-01', 'OIL.11': 'OIL_2006-12-01', 'GAS.5': 'GAS_2006-06-01', 'OIL.9': 'OIL_2006-10-01', 'OIL.7': 'OIL_2006-08-01', 'GAS.2': 'GAS_2006-03-01', 'OIL.2': 'OIL_2006-03-01', 'GAS.9': 'GAS_2006-10-01', 'GAS.7': 'GAS_2006-08-01', 'GAS.3': 'GAS_2006-04-01', 'GAS.0': 'GAS_2006-01-01', 'GAS.10': 'GAS_2006-11-01', 'OIL.0': 'OIL_2006-01-01', 'OIL.4': 'OIL_2006-05-01', 'OIL.8': 'OIL_2006-09-01', 'OIL.3': 'OIL_2006-04-01', 'GAS.1': 'GAS_2006-02-01', 'GAS.6': 'GAS_2006-07-01'}
2007

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,5,8,15,16,17,18,19,20,27,29,30,33,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2007-06-01', 'GAS.8': 'GAS_2007-09-01', 'GAS.11': 'GAS_2007-12-01', 'OIL.6': 'OIL_2007-07-01', 'OIL.1': 'OIL_2007-02-01', 'OIL.10': 'OIL_2007-11-01', 'GAS.4': 'GAS_2007-05-01', 'OIL.11': 'OIL_2007-12-01', 'GAS.5': 'GAS_2007-06-01', 'OIL.9': 'OIL_2007-10-01', 'OIL.7': 'OIL_2007-08-01', 'GAS.2': 'GAS_2007-03-01', 'OIL.2': 'OIL_2007-03-01', 'GAS.9': 'GAS_2007-10-01', 'GAS.7': 'GAS_2007-08-01', 'GAS.3': 'GAS_2007-04-01', 'GAS.0': 'GAS_2007-01-01', 'GAS.10': 'GAS_2007-11-01', 'OIL.0': 'OIL_2007-01-01', 'OIL.4': 'OIL_2007-05-01', 'OIL.8': 'OIL_2007-09-01', 'OIL.3': 'OIL_2007-04-01', 'GAS.1': 'GAS_2007-02-01', 'GAS.6': 'GAS_2007-07-01'}
2008
Index(['API_COUNTY', 'API_NUMBER', 'SUFFIX', 'WELL_NAME', 'WELL_NO',
       '  OPER_NO', 'OPER_SUFFIX', 'OPERATOR', 'ME', 'SECTION', 'TWP', 'RAN',
       'Q4', 'Q3', 'Q2', 'Q1', 'LATITUDE', 'LONGITUDE', 'OTC_COUNTY',
       'OTC_LEASE_NO', 'OTC_SUB_NO', 'OTC_MERGE', 'POOL_NO', 'CODE',
       'FORMATION', 'OFB', 'ALLOWABLE_CLASS', 'ALLOWABLE_TYPE', ' PURCH_NO',
       'PURCHASER', 'PURCH_SUFFIX', 'OFB.1', 'YEAR', 'JAN', 'OIL.0', 'GAS.0',
       'FEB', 'OIL.1', 'GAS.1', 'MAR', 'OIL.2', 'GAS.2', 'APR', 'OIL.3',
       'GAS.3', 'MAY', 'OIL.4', 'GAS.4', 'JUN', 'OIL.5', 'GAS.5', 'JUL',
       'OIL.6', 'GAS.6', 'AUG', 'OIL.7', 'GAS.7', 'SEP', 'OIL.8', 'GAS.8',
       'OCT', 'OIL.9', 'GAS.9', 'NOV', 'OIL.10', 'GAS.10', 'DEC', 'OIL.11',
       'GAS.11'],
      dtype='object')
{'OIL.5': 'OIL_2008-06-01', 'GAS.8': 'GAS_2008-09-01', 'GAS.11': 'GAS_2008-12-01', 'OIL.6': 'OIL_2008-07-01', 'OIL.1': 'OIL_2008-02-01', 'OIL.10': 'OIL_2008-11-01', 'GAS.4': 'GAS_2008-05-01', 'OIL.11': 'OIL_2008-12-01', 'GAS.5': 'GAS_2008-06-01', 'OIL.9': 'OIL_2008-10-01', 'OIL.7': 'OIL_2008-08-01', 'GAS.2': 'GAS_2008-03-01', 'OIL.2': 'OIL_2008-03-01', 'GAS.9': 'GAS_2008-10-01', 'GAS.7': 'GAS_2008-08-01', 'GAS.3': 'GAS_2008-04-01', 'GAS.0': 'GAS_2008-01-01', 'GAS.10': 'GAS_2008-11-01', 'OIL.0': 'OIL_2008-01-01', 'OIL.4': 'OIL_2008-05-01', 'OIL.8': 'OIL_2008-09-01', 'OIL.3': 'OIL_2008-04-01', 'GAS.1': 'GAS_2008-02-01', 'GAS.6': 'GAS_2008-07-01'}
2009
2010
2011
2012

E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,2,5,8,15,16,17,18,19,20,21,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

2013
2014
2015

In [6]:
for year in production_data.keys():
    print(production_data[year].size)

226744
409752
1074640
1205904
1271928
1047592
723856
1450232
1421728
1485456
1738464
1928472
2423568
1922312
1892632
2122512
2237256
2171344
2738848
2506056
2603776
2834502
3420252
2753520
35619
2745534
2738670
2718672

In [7]:
def filter_data(row):
    buffer = []
    for val in row:
        val_parsed = None
        try:
            val_parsed = int(val)
        except ValueError:
            val_parsed = 0
        buffer.append(val_parsed)
    return np.array(buffer, dtype=np.int32)

In [8]:
oil_prod_dfs = []
for year in range(1987, 2016):
    if year != 1994:
        oil_data = {}
        filter_col = [col for col in list(production_data[year]) if col.startswith('OIL')]
        print(len(production_data[year].index))
        for i in range(1, len(production_data[year].index)):
            row = production_data[year].iloc[[i]]
            api_num = row["API_NUMBER"].values.astype(np.int32)[0]
            pdata = filter_data(row[filter_col].values[0])
            oil_data[api_num] = pdata
        months = pd.date_range(start=str(year)+'-01-01', periods=12, freq='M')
        oil_dataframe = pd.DataFrame.from_dict(oil_data)
        oil_dataframe = oil_dataframe.set_index(months)
        oil_prod_dfs.append(oil_dataframe)

4049
7317
19190
21534
22713
18707
12926
25897
25388
26526
31044
34437
43278
34327
33797
37902
39951

ValueError: cannot convert float NaN to integer

In [9]:
oil_all_df = pd.concat(oil_prod_dfs).fillna(0)

,1,2,3,4,5,6,7,8,9,10,...,70034,70038,70096,70103,75014,75024,77043,97002,97113,97114
1987-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-02-28,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
oil_all_df.head(12*100)

,1,2,3,4,5,6,7,8,9,10,...,70034,70038,70096,70103,75014,75024,77043,97002,97113,97114
1987-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-02-28,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-06-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-07-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-08-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-09-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-10-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-11-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1987-12-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-02-29,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,179.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-06-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-07-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-08-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-09-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-10-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-11-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988-12-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-02-28,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989-06-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2001-07-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001-08-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001-09-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001-10-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001-11-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001-12-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-02-28,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-06-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-07-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-08-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-09-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-10-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-11-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2002-12-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-01-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-02-28,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-03-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-04-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-05-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-06-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-07-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-08-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-09-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-10-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-11-30,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2003-12-31,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
oil_all_df.to_hdf('../processed/oil/oil_data.h5','table', mode="w")